-- ==========================================
-- Migration 010: Small/Large barcode label variants
-- ==========================================
-- tools.barcode_image_url / linear_barcode_image_url (migrations 004, 008) hold the "medium"
-- size (15mm Data Matrix / scale-3 Code 128) -- unchanged, still generated by default. This
-- adds a small and large variant of each, generated and stored alongside it, so a batch print
-- run can pick whichever size actually fits a given tool instead of one compromise size for
-- everything. Sizes are anchored to scripts/generate-size-test-sheet.js's own already-
-- validated candidate range (3-20mm) rather than arbitrary numbers -- see BARCODE_SIZES in
-- server.js for the exact small/medium/large values.

ALTER TABLE tools ADD COLUMN IF NOT EXISTS barcode_image_url_small TEXT;
ALTER TABLE tools ADD COLUMN IF NOT EXISTS barcode_image_url_large TEXT;
ALTER TABLE tools ADD COLUMN IF NOT EXISTS linear_barcode_image_url_small TEXT;
ALTER TABLE tools ADD COLUMN IF NOT EXISTS linear_barcode_image_url_large TEXT;
